{{ if .Values.schema.enabled }}
{{ range .Values.schema.containers }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.appName }}-{{ . }}-load
spec:
  template:
    spec:
      containers:
        - name: {{ $.Values.appName }}-{{ . }}-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: db/{{ . }}.{{ $.Values.schema.dbExtension }}

          {{ range $key, $val := $.Values.schema.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{ end }}
      restartPolicy: Never
{{ end }}
{{ end }}