apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.appname }}
          ports:
            - containerPort: 80
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
            - value: {{ $val }}
          {{- end }}

