apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    {{ - include "common.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}